//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kritzel.HTTPServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kritzel.HTTPServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .css text/css
        ///.htm text/html
        ///.html text/html
        ///.htmls text/html
        ///.js text/javascript
        ///.shtml text/html
        ///.txt text/plain
        ///
        ///.exe application/octec-stream
        ///.gz application/x-gzip
        ///.tar application/x-tar
        ///.gtar application/x-gtar
        ///.pdf application/pdf
        ///.tgz application/gnutar
        ///.zip application/zip
        ///
        ///.bmp image/bmp
        ///.gif image/gif
        ///.jpe image/jpeg
        ///.jpg image/jpeg
        ///.jpeg image/jpeg
        ///.png image/png
        ///.tif image/tiff
        ///
        ///.mp3 audio/mpeg3
        ///.wav audio/wav
        ///.mp4 video/mp4.
        /// </summary>
        internal static string MimeTypes {
            get {
                return ResourceManager.GetString("MimeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 Continue
        ///101 Switching Protocols
        ///102 Processing
        ///200 OK
        ///201 Created
        ///202 Accepted
        ///203 Non-Authorized INformation
        ///204 No Content
        ///205 Reset Content
        ///206 Partial Content
        ///207 Multi-Status
        ///208 Already Reported
        ///226 IM Used
        ///300 Multiple Choises
        ///301 Moved Permanently
        ///302 Found
        ///303 See Other
        ///304 Not Modified
        ///305 Use Proxy
        ///307 Temporary Redirect
        ///308 Permanent Redirect
        ///400 Bad Request
        ///401 Unauthorized
        ///402 Payment Required
        ///403 Forbidden
        ///404 Not Found
        ///405 Method Not Allowed
        ///406 Not Acceptable [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusCodes {
            get {
                return ResourceManager.GetString("StatusCodes", resourceCulture);
            }
        }
    }
}
